export const books = [
    { id: 1, imageUrl: "https://covers.openlibrary.org/b/isbn/0451524934-L.jpg", title: "1984", author: "George Orwell", rating: 4, mediaType: "Book", availability: "Available", location: "TFDL", language: "English", addedDate: "1949-06-08", genre: "Dystopian", description: "A novel about the dangers of totalitarianism, set in a society where the government has complete control over every aspect of life." },
    { id: 2, imageUrl: "https://covers.openlibrary.org/b/isbn/0060850523-L.jpg", title: "Brave New World", author: "Aldous Huxley", rating: 1, mediaType: "Ebook", availability: "Checked Out", location: "Location 1", language: "English", addedDate: "1932-08-18", genre: "Dystopian", description: "A dystopian novel which anticipates developments in reproductive technology, sleep-learning, psychological manipulation, and classical conditioning." },
    { id: 3, imageUrl: "https://covers.openlibrary.org/b/isbn/9780451419439-L.jpg", title: "Les Misérables", author: "Victor Hugo", rating: 3, mediaType: "Audiobook", availability: "Available", location: "Location 2", language: "French", addedDate: "1862-04-03", genre: "Classic", description: "An epic novel concerning the struggles of several characters, particularly the ex-convict Jean Valjean, to live decent lives." },
    { id: 4, imageUrl: "https://covers.openlibrary.org/b/isbn/0743273567-L.jpg", title: "The Great Gatsby", author: "F. Scott Fitzgerald", rating: 5, mediaType: "Book", availability: "Available", location: "TFDL", language: "English", addedDate: "1925-04-10", genre: "Classic", description: "A novel set in the Jazz Age on Long Island, near New York City, depicting first-person narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby." },
    { id: 5, imageUrl: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg", title: "To Kill a Mockingbird", author: "Harper Lee", rating: 4, mediaType: "Ebook", availability: "Checked Out", location: "Location 1", language: "English", addedDate: "1960-07-11", genre: "Classic", description: "A novel about the serious issues of rape and racial inequality, but it is also a story about the loss of innocence and the complexities of human nature." },
    { id: 6, imageUrl: "https://covers.openlibrary.org/b/isbn/9780156027328-L.jpg", title: "Life of Pi", author: "Yann Martel", rating: 3, mediaType: "Book", availability: "Available", location: "Location 2", language: "English", addedDate: "2001-09-11", genre: "Fiction", description: "A story about a young Indian boy named Pi Patel, who survives 227 days after a shipwreck while stranded on a lifeboat in the Pacific Ocean with a Bengal tiger." },
    { id: 7, imageUrl: "https://covers.openlibrary.org/b/isbn/0316769487-L.jpg", title: "The Catcher in the Rye", author: "J.D. Salinger", rating: 2, mediaType: "Audiobook", availability: "Available", location: "TFDL", language: "English", addedDate: "1951-07-16", genre: "Fiction", description: "A novel about a few days in the life of a disaffected 16-year-old boy, Holden Caulfield, after he has been expelled from prep school." },
    { id: 8, imageUrl: "https://covers.openlibrary.org/b/isbn/9780399501487-L.jpg", title: "Lord of the Flies", author: "William Golding", rating: 3, mediaType: "Ebook", availability: "Available", location: "Location 2", language: "English", addedDate: "1954-09-17", genre: "Fiction", description: "A novel about a group of British boys stranded on an uninhabited island and their disastrous attempt to govern themselves." },
    { id: 9, imageUrl: "https://covers.openlibrary.org/b/isbn/0451526341-L.jpg", title: "Animal Farm", author: "George Orwell", rating: 5, mediaType: "Book", availability: "Checked Out", location: "TFDL", language: "English", addedDate: "1945-08-17", genre: "Allegory", description: "An allegorical novella reflecting events leading up to the Russian Revolution of 1917 and then on into the Stalinist era of the Soviet Union." },
    { id: 10, imageUrl: "https://covers.openlibrary.org/b/isbn/9780486284736-L.jpg", title: "Pride and Prejudice", author: "Jane Austen", rating: 5, mediaType: "Ebook", availability: "Available", location: "Location 1", language: "English", addedDate: "1813-01-28", genre: "Romance", description: "A romantic novel of manners that follows the character development of Elizabeth Bennet, the dynamic protagonist of the book." },
    { id: 11, imageUrl: "https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg", title: "Le Petit Prince", author: "Antoine de Saint-Exupéry", rating: 4, mediaType: "Book", availability: "Available", location: "TFDL", language: "French", addedDate: "1943-04-06", genre: "Children's", description: "A novella about a young prince who visits various planets in space, including Earth, and addresses themes of loneliness, friendship, love, and loss." },
    { id: 12, imageUrl: "https://covers.openlibrary.org/b/isbn/9780747532743-L.jpg", title: "Harry Potter and the Philosopher’s Stone", author: "J.K. Rowling", rating: 5, mediaType: "Audiobook", availability: "Available", location: "Location 2", language: "English", addedDate: "1997-06-26", genre: "Fantasy", description: "The first novel in the Harry Potter series, following a young wizard, Harry Potter, and his friends as they attend Hogwarts School of Witchcraft and Wizardry." },
    { id: 13, imageUrl: "https://covers.openlibrary.org/b/isbn/9780486278070-L.jpg", title: "The Picture of Dorian Gray", author: "Oscar Wilde", rating: 5, mediaType: "Book", availability: "Checked Out", location: "TFDL", language: "English", addedDate: "1890-07-01", genre: "Gothic", description: "A philosophical novel about a man who sells his soul so that a painting of him will age and fade instead of his own body." },
    { id: 14, imageUrl: "https://covers.openlibrary.org/b/isbn/9780679732761-L.jpg", title: "The Alchemist", author: "Paulo Coelho", rating: 3, mediaType: "Ebook", availability: "Available", location: "Location 1", language: "English", addedDate: "1988-04-01", genre: "Fantasy", description: "An allegorical novel about a young Andalusian shepherd named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure." },
    { id: 15, imageUrl: "https://covers.openlibrary.org/b/isbn/9782253006329-L.jpg", title: "Vingt Mille Lieues Sous La Mer", author: "Jules Verne", rating: 2, mediaType: "Audiobook", availability: "Checked Out", location: "Location 2", language: "French", addedDate: "1869-11-17", genre: "Sci-Fi", description: "A classic science fiction adventure novel telling the story of Captain Nemo and his submarine, the Nautilus, as seen from the perspective of Professor Pierre Aronnax." },
    { id: 16, imageUrl: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg", title: "The Handmaid’s Shadow", author: "Margaret Dunn", rating: 5, mediaType: "Book", availability: "Available", location: "TFDL", language: "English", addedDate: "2001-05-15", genre: "Dystopian", description: "A fictional story following the themes of Margaret Atwood's work." },
    { id: 17, imageUrl: "https://covers.openlibrary.org/b/isbn/9780062316110-L.jpg", title: "Ready Player One", author: "Ernest Cline", rating: 4, mediaType: "Ebook", availability: "Available", location: "Location 1", language: "English", addedDate: "2011-08-16", genre: "Sci-Fi", description: "Set in a dystopian 2045, the novel follows protagonist Wade Watts on his search for an Easter egg in a worldwide virtual reality game." },
    { id: 18, imageUrl: "https://covers.openlibrary.org/b/isbn/9780140447422-L.jpg", title: "Germinal", author: "Émile Zola", rating: 5, mediaType: "Book", availability: "Available", location: "Location 2", language: "French", addedDate: "1885-03-25", genre: "Classic", description: "A brutally realistic novel about a coal miners' strike in northern France in the 1860s." },
    { id: 19, imageUrl: "https://covers.openlibrary.org/b/isbn/9780439023528-L.jpg", title: "The Hunger Games", author: "Suzanne Collins", rating: 4, mediaType: "Audiobook", availability: "Checked Out", location: "TFDL", language: "English", addedDate: "2008-09-14", genre: "Dystopian", description: "In a dystopian future, the totalitarian nation of Panem is divided into 12 districts and the Capitol. Each year, two young representatives are selected to participate in The Hunger Games." },
    { id: 20, imageUrl: "https://covers.openlibrary.org/b/isbn/9780141187761-L.jpg", title: "A Farewell to Arms", author: "Ernest Hemingway", rating: 3, mediaType: "Book", availability: "Available", location: "Location 1", language: "English", addedDate: "1929-09-27", genre: "Classic", description: "A novel set during the Italian campaign of World War I, about a first-person account of an American, Frederic Henry, serving as a lieutenant in the ambulance corps of the Italian Army." },
    { id: 21, imageUrl: "https://covers.openlibrary.org/b/isbn/9780307387899-L.jpg", title: "The Road", author: "Cormac McCarthy", rating: 4, mediaType: "Ebook", availability: "Available", location: "Location 2", language: "English", addedDate: "2006-09-26", genre: "Post-apocalyptic", description: "A novel about a father and his young son walking alone through burned America, heading south for the coast, although they don't know what, if anything, awaits them there." },
    { id: 22, imageUrl: "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg", title: "The Count of Monte Cristo", author: "Alexandre Dumas", rating: 5, mediaType: "Book", availability: "Available", location: "TFDL", language: "English", addedDate: "1846-06-20", genre: "Adventure", description: "An adventure novel about a man who is unjustly imprisoned, escapes, acquires a fortune, and sets about getting revenge on those responsible for his imprisonment." },
    { id: 23, imageUrl: "https://covers.openlibrary.org/b/isbn/9780140283334-L.jpg", title: "Lord of the Flies", author: "William Golding", rating: 2, mediaType: "Ebook", availability: "Checked Out", location: "Location 1", language: "English", addedDate: "1954-09-17", genre: "Allegory", description: "A novel about a group of British boys stranded on an uninhabited island and their disastrous attempt to govern themselves." },
    { id: 24, imageUrl: "https://covers.openlibrary.org/b/isbn/9780486266893-L.jpg", title: "Candide", author: "Voltaire", rating: 5, mediaType: "Book", availability: "Available", location: "Location 2", language: "French", addedDate: "1759-01-01", genre: "Satire", description: "A French satire that begins with a young man, Candide, who is living a sheltered life in an Edenic paradise and being indoctrinated with Leibnizian optimism." },
    { id: 25, imageUrl: "https://covers.openlibrary.org/b/isbn/9780385504201-L.jpg", title: "The Da Vinci Code", author: "Dan Brown", rating: 4, mediaType: "Ebook", availability: "Available", location: "TFDL", language: "English", addedDate: "2003-03-18", genre: "Thriller", description: "A mystery thriller novel that follows symbologist Robert Langdon and cryptologist Sophie Neveu as they investigate a murder in Paris's Louvre Museum." },
    { id: 26, imageUrl: "https://covers.openlibrary.org/b/isbn/9780439139595-L.jpg", title: "Harry Potter and the Goblet of Fire", author: "J.K. Rowling", rating: 5, mediaType: "Book", availability: "Checked Out", location: "Location 1", language: "English", addedDate: "2000-07-08", genre: "Fantasy", description: "The fourth novel in the Harry Potter series, following Harry as he is mysteriously entered into the Triwizard Tournament." },
    { id: 28, imageUrl: "https://covers.openlibrary.org/b/isbn/9782070360024-L.jpg", title: "L'étranger", author: "Albert Camus", rating: 4, mediaType: "Ebook", availability: "Available", location: "TFDL", language: "French", addedDate: "1942-04-16", genre: "Absurdist", description: "A novel that explores themes of absurdity, the meaninglessness of human life, and the indifference of the universe." },
    { id: 29, imageUrl: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg", title: "One Hundred Years of Solitude", author: "Gabriel García Márquez", rating: 5, mediaType: "Book", availability: "Checked Out", location: "Location 1", language: "English", addedDate: "1967-05-30", genre: "Magical Realism", description: "The multi-generational story of the Buendía family, whose patriarch, José Arcadio Buendía, founded the town of Macondo." },
    { id: 30, imageUrl: "https://covers.openlibrary.org/b/isbn/9780143039433-L.jpg", title: "The Grapes of Wrath", author: "John Stejnbeck", rating: 3, mediaType: "Ebook", availability: "Available", location: "Location 2", language: "English", addedDate: "2007-05-03", genre: "Classic", description: "A novel about the Joads, a poor family of tenant farmers driven from their Oklahoma home by drought, economic hardship, and changes in the industry." },
    { id: 31, imageUrl: "https://covers.openlibrary.org/b/isbn/9781594480003-L.jpg", title: "The Kite Runner", author: "Khaled Hosseini", rating: 5, mediaType: "Book", availability: "Available", location: "TFDL", language: "English", addedDate: "2003-06-01", genre: "Historical Fiction", description: "A novel about the unlikely friendship between a wealthy boy and the son of his father's servant, set against a backdrop of tumultuous events, from the fall of Afghanistan's monarchy through the Soviet invasion." },
    { id: 32, imageUrl: "https://covers.openlibrary.org/b/isbn/9780141187761-L.jpg", title: "For Whom the Bell Tolls", author: "Ernest Hemingway", rating: 4, mediaType: "Ebook", availability: "Checked Out", location: "Location 1", language: "English", addedDate: "1940-10-21", genre: "War", description: "A novel about a young American volunteer attached to a Republican guerrilla unit during the Spanish Civil War." },
    { id: 33, imageUrl: "https://covers.openlibrary.org/b/isbn/9780679735779-L.jpg", title: "American Psycho", author: "Bret Easton Ellis", rating: 2, mediaType: "Audiobook", availability: "Available", location: "Location 2", language: "English", addedDate: "1991-04-29", genre: "Horror", description: "A controversial novel that follows Patrick Bateman, a wealthy and materialistic yuppie and serial killer in late 1980s New York City." },
    { id: 34, imageUrl: "https://covers.openlibrary.org/b/isbn/9782070413119-L.jpg", title: "Madame Bovary", author: "Gustave Flaubert", rating: 5, mediaType: "Book", availability: "Available", location: "TFDL", language: "French", addedDate: "1856-04-15", genre: "Realist", description: "A novel that focuses on a doctor's wife, Emma Bovary, who has adulterous affairs and lives beyond her means in order to escape the banalities and emptiness of provincial life." },
    { id: 35, imageUrl: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg", title: "Sapiens: A Brief History of Humankind", author: "Yuval Noah Harari", rating: 3, mediaType: "Ebook", availability: "Available", location: "Location 1", language: "English", addedDate: "2011-09-04", genre: "Non-fiction", description: "A book that surveys the history of humankind, from the Stone Age up to the present day." },
];

/**
 * Finds a book in the database by its ID.
 * @param {number} id - The ID of the book to find.
 * @returns {object | undefined} The book object if found, or undefined.
 */
export const findBookById = (id) => books.find(book => book.id === id);