export const styles = {
  appContainer: {
    minHeight: "100vh",
    backgroundColor: "#f5f5f5",
    fontFamily: "Arial, sans-serif",
  },
  navbar: {
    backgroundColor: "#000",
    padding: "0",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  navContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    maxWidth: "1200px",
    margin: "0 auto",
    height: "70px",
    paddingLeft: "0px",
    paddingRight: "0px",
  },
  navTitle: {
    flex: 1,
  },
  titleText: {
    color: "#fff",
    margin: 0,
    fontSize: "24px",
    fontWeight: "bold",
  },
  navLinks: {
    flex: 2,
    display: "flex",
    justifyContent: "center",
    gap: "30px",
  },
  navLink: {
    color: "#fff",
    backgroundColor: "#000",
    border: "none",
    fontSize: "16px",
    padding: "8px 16px",
    borderRadius: "4px",
    transition: "background-color 0.3s",
    cursor: "pointer",
  },
  navLinkActive: {
    backgroundColor: "#333",
    fontWeight: "bold",
  },
  navRight: {
    flex: 1,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: "15px",
  },
  iconButton: {
    backgroundColor: "#000",
    border: "2px solid #fff",
    color: "#fff",
    padding: "8px 12px",
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.3s",
  },
  profileButton: {
    backgroundColor: "#000",
    color: "#fff",
    border: "2px solid #fff",
    padding: "8px 16px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "background-color 0.3s",
  },
  pageContainer: {
    padding: "40px 20px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  contentBox: (textSize) => ({
    backgroundColor: "#fff",
    padding: "40px",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    fontSize: textSize === "large" ? "18px" : "16px",
  }),
  popupBackdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  popupContent: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.2)",
    minWidth: "400px",
    maxWidth: "600px",
    maxHeight: "80vh",
    overflow: "auto",
    animation: "fadeIn 0.3s ease-in",
  },
  popupHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px",
    borderBottom: "1px solid #eee",
  },
  popupTitle: {
    margin: 0,
    fontSize: "20px",
    fontWeight: "bold",
    color: "#000",
  },
  popupCloseButton: {
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#666",
    padding: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "color 0.2s",
  },
  popupBody: {
    padding: "20px",
    color: "#333",
  },
};
